spring:

  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tengjiao-part-sample?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver # `com.mysql.cj.jdbc.Drive` for mysql5.7+


# 以下为自定义属性
config:
  # 这种格式仅在Idea下运行时才能找到正确目录
  #path: ./tengjiao-part-samples/tengjiao-part-sample-ssj/src/main/resources/setting.properties
  # 这种格式仅在Idea下单元测试运行时才能找到正确目录
  path: ./src/main/resources/setting.properties